%YAML:1.0
#YAML1.0に則ります.
#ID=-1はデフォルト設定値とします。
#インデントを守ってください.{}で囲みます.
#{}内は","区切りとします.
#少数点でEを利用するときは必ず小数第一位以上記載のこと　例1.0E-02
---
LMT:
 - {ID: -1,
   TYPE: 1,
   PKG_SIZE: 44.00,
   REF_SIZE: 30.6250,
   REF_DIAM: 4.3750,
   LEAG_LENGTH: 21.00,
   FDP_LENGTH: 17.00,
   AR_SIZE: 21.00,
   STY: [-7.3346E-07, -1.6665E-06, 1.9630E-01, 4.5375E-01, 20.0],
   STX: [-7.5399E-07, -9.3718E-07, 1.9799E-01, -9.5812E-02, 20.0]}

   
